#!/usr/bin/env python

import sys

keypad = [
        "1",
        "2abc",
        "3def",
        "4ghi",
        "5jkl",
        "6mno",
        "7pqrs",
        "8tuv",
        "9wxyz",
        "0"]

sum = 0
password = sys.argv[1]
for c in password:
    for key in keypad:
        if c in key:
            digit  = int(key[0])
            pos =  key.index(c)
            sum += digit * (pos+1)
print sum
